export const SET_CATEGORIES_ACTION_TYPE = 'SET_CATEGORIES_ACTION_TYPE';
export const ADD_PAPER_ACTION_TYPE = 'ADD_PAPER_ACTION_TYPE';
export const REMOVE_PAPER_ACTION_TYPE = 'REMOVE_PAPER_ACTION_TYPE';
