export const SET_CATEGORIES_ACTION_TYPE = 'SET_CATEGORIES_ACTION_TYPE';
export const ADD_PAPER_ACTION_TYPE = 'ADD_PAPER_ACTION_TYPE';
export const EXTRACT_PAPER_ACTION_TYPE = 'EXTRACT_PAPER_ACTION_TYPE';
