version: '3.5'
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "${EXTERNAL_PORT}:${PORT}"
      - "${EXTERNAL_PORT}:${PORT}"
    environment:
      - NODE_ENV="production"
      - PORT=${PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    restart: always
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodbdata:/data/db

  admin-mongo:
    # mongodb://ROMAN:12345@mongo
    image: adicom/admin-mongo
    ports:
      - "${ADMIN_MONGO_PORT}:${ADMIN_MONGO_PORT}"
    environment:
      - PORT=${ADMIN_MONGO_PORT}
      - HOST=mongo
    depends_on:
      - mongo

  redis:
    image: redis
    volumes:
      - redis_data:/data

  bullboard:
    image: deadly0/bull-board
    ports:
      - 9181:3000
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BULL_PREFIX: bull
    depends_on:
      - redis

volumes:
  mongodbdata:
  redis_data:
