export const SET_TODOS_ACTION_TYPE = 'SET_TODOS_ACTION_TYPE';
export const ADD_TODO_ITEM_ACTION_TYPE = 'ADD_TODO_ITEM_ACTION_TYPE';
export const REMOVE_TODO_ITEM_ACTION_TYPE = 'REMOVE_TODO_ITEM_ACTION_TYPE';
export const CHANGE_STATUS_TODO_ITEM_ACTION_TYPE = 'CHANGE_STATUS_TODO_ITEM_ACTION_TYPE';